"""empty message

Revision ID: 19ae67f64271
Revises: 234c097a6718
Create Date: 2019-01-06 18:24:11.311600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ae67f64271'
down_revision = '234c097a6718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_barang',
    sa.Column('id_barang', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.String(length=60), nullable=True),
    sa.Column('harga_barang', sa.Integer(), nullable=True),
    sa.Column('garansi_barang', sa.Boolean(), nullable=True),
    sa.Column('foto_barang', sa.String(length=100), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_jurusan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_jurusan'], ['tb_jurusan.id_jurusan'], ),
    sa.ForeignKeyConstraint(['id_user'], ['tb_users.id_user'], ),
    sa.PrimaryKeyConstraint('id_barang')
    )
    op.create_index(op.f('ix_tb_barang_foto_barang'), 'tb_barang', ['foto_barang'], unique=False)
    op.create_index(op.f('ix_tb_barang_harga_barang'), 'tb_barang', ['harga_barang'], unique=False)
    op.create_index(op.f('ix_tb_barang_nama_barang'), 'tb_barang', ['nama_barang'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_barang_nama_barang'), table_name='tb_barang')
    op.drop_index(op.f('ix_tb_barang_harga_barang'), table_name='tb_barang')
    op.drop_index(op.f('ix_tb_barang_foto_barang'), table_name='tb_barang')
    op.drop_table('tb_barang')
    # ### end Alembic commands ###
